name: Librecad3 Builders
on:
  push:
    branches:
    - main
jobs:
  windowsInstall:
    name: Building LibreCAD3 on windows runner
    runs-on: windows-latest
    
    steps:
      - name: Disable Chocolatey confirmations
        run: choco feature enable -n=allowGlobalConfirmation &

      - name: Install Visual Studio 2019 with tools
        run: choco install visualstudio2019community --package-parameters='"--add Microsoft.VisualStudio.Component.VC.CMake.Project Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.Windows10SDK.19041"'
      
      - name: Clone Repo and enter
        run: |
            git clone --recursive https://github.com/LibreCAD/LibreCAD_3.git
            cd LibreCAD_3
      
      - name: Installing conan and getting its dependencies. If it fails, modify the profile compiler version and try again
        run: |
            pip install conan
            mkdir conan
            cd conan
            conan install ..
            if NOT %errorlevel% == "0" (
            conan profile update settings.compiler.version=16  default
            conan install ..
            )

      - name: preparing Qt5 env
        run: |
            cd ..\..
            mkdir Qt

      - name: Install Qt5
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.2'
          host: 'windows'
          arch: 'win64_msvc2017_64'
          dir: ${{ github.workspace }}\Qt

      - name: Set env variables and path appends
        run: |
          setx QTDIR "%cd%\Qt\5.15.2\msvc2019_64"
          setx QT_QPA_PLATFORM_PLUGIN_PATH "%QTDIR%\plugins\platforms\"
          Powershell.exe -Command "[Environment]::SetEnvironmentVariable('Path', $env:Path + ';%cd%\Qt\5.15.2\msvc2019_64;%cd%\LibreCAD_3\out\build\x64-Debug\lib;%cd%\Qt\5.15.2\msvc2019_64\bin', 'User')"

      - name: Building the project
        run: |
          

